name: todo-list

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-fastapi
    restart: unless-stopped
    command: fastapi dev api_core/main.py --host 0.0.0.0 --port 3000
    # env_file:
    #   - .env
    environment:
      - ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DATABASE_URL
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/backend/:/app/
    networks:
      - todo-network

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: todo-postgres-db
    restart: unless-stopped
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  todo-network:
    name: todo-network
    driver: bridge