"""Initial migration

Revision ID: 80de127c9db2
Revises: 
Create Date: 2025-01-08 07:43:10.529079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80de127c9db2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todoitems_due_date', table_name='todoitems')
    op.drop_index('ix_todoitems_id', table_name='todoitems')
    op.drop_index('ix_todoitems_priority', table_name='todoitems')
    op.drop_index('ix_todoitems_status', table_name='todoitems')
    op.drop_index('ix_todoitems_title', table_name='todoitems')
    op.drop_table('todoitems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoitems',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todoitems_pkey')
    )
    op.create_index('ix_todoitems_title', 'todoitems', ['title'], unique=False)
    op.create_index('ix_todoitems_status', 'todoitems', ['status'], unique=False)
    op.create_index('ix_todoitems_priority', 'todoitems', ['priority'], unique=False)
    op.create_index('ix_todoitems_id', 'todoitems', ['id'], unique=False)
    op.create_index('ix_todoitems_due_date', 'todoitems', ['due_date'], unique=False)
    # ### end Alembic commands ###
